"""Stable config and MoodHistory model update

Revision ID: 1f990c8203b6
Revises: 39677ef60084
Create Date: 2025-10-27 19:55:37.952909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1f990c8203b6'
down_revision = '39677ef60084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_history', schema=None) as batch_op:
        batch_op.alter_column('mood_data',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_history', schema=None) as batch_op:
        batch_op.alter_column('mood_data',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###
