"""Fix CSRF/JSON config and update MoodHistory model

Revision ID: 39677ef60084
Revises: 8c8e669be177
Create Date: 2025-10-27 19:28:54.284527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39677ef60084'
down_revision = '8c8e669be177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_history', schema=None) as batch_op:
        batch_op.alter_column('mood_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_history', schema=None) as batch_op:
        batch_op.alter_column('mood_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
