"""Change mood_data from JSON to Text for SQLite

Revision ID: 8c8e669be177
Revises: b844d0c07417
Create Date: 2025-10-27 16:47:41.833591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8c8e669be177'
down_revision = 'b844d0c07417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_history', schema=None) as batch_op:
        batch_op.alter_column('mood_data',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_history', schema=None) as batch_op:
        batch_op.alter_column('mood_data',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###
